config/routes.rb
Todo::Application.routes.draw do
  get "users/new"
  get "sessions/new"

  

  resources :items
  resources :sessions
  resources :list do
    delete 'checked'
  end
  resources :users
  
  root to: "list#index"
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'
  get '/log_in' => 'sessions#new'
  post '/log_in' => 'sessions#create'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
end

app/models/auth_token.rb
require 'securerandom'

class AuthToken < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :token, uniqueness: true
  before_create :generate_token

  def generate_token
  	begin
  		self.token = SecureRandom.hex
  	end while self.class.exists?(token: token)
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
  after_initialize :init

  def init
  	self.done = false if self.done.nil?
  end
end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :items, dependent: :destroy
	validates :title, presence: true, length: {minimum: 3, maximum: 50}
	validates :user_id, presence: true
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :password, :on => :create
  validates :username, uniqueness: true
  has_many :lists, dependent: :destroy
  has_many :auth_tokens, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception

  private 
	def authenticate
		#Try a session first, then try an auth token
		if session[:user_id]
			@user = User.find(session[:user_id])
			return
		else
			 authenticate_with_http_token  do |token, options|
				auth_token = AuthToken.find_by_token(token)
				if auth_token 
					@user = auth_token.user
					return
				end
			end
		end

		#if it reaches this point we are not authenticated so respond approriately
		respond_to do |format|
			format.html {render 'pages/unauthorized'}
			format.json {head :unauthorized}
		end
		
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :authenticate
	def update
		@item = Item.find(params[:id])

		#Validate that the user is updating an item in their own lists
		if @item.list.user != @user
			return head :unauthorized
		end

		if @item.update(params[:item].permit(:name,:done))
			respond_to do |format|
				format.html
				format.json {render :json => @item, :status => :ok}
			end
		end
	end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
	respond_to :json
	#TODO: compute recent feeds once and cache
	before_action :authenticate
	before_action :recent_lists, only: [:edit,:show,:new,:index]

	def recent_lists
		@recent_lists = @user.lists.order("created_at DESC").limit(10)
	end

	def create
		@list = @user.lists.new({:title => params[:title]})
		@list.items.new(params[:items]) if params[:items]
		if @list.save
			respond_to do |format|
				format.html
				format.json{render :json => @list, :status => :created, :location => @list}
			end
		end
	end

	def show
		#TODO BADDDD FIX...
		@lists = @user.lists.order('created_at DESC')
		@list = @user.lists.find(params[:id])
		@breadcrumbs = ['Lists', @list.title]

		respond_to do |format|
			format.html
			format.json {render json: @list.to_json(:include => :items) }
		end
	end

	def new

	end

	def index
		@lists = @user.lists.order('created_at DESC')
		listJson = {:lists => @lists}
		respond_to do |format|
			format.html
			format.json  {render json: listJson}
		end
	end

	def destroy

		respond_to do |format|
			@list = @user.lists.find(params[:id])
			if @list.destroy
				format.json {render nothing: true}
				format.html {redirect_to("/list")}
			else
				format.html {redirect_to("/list")}
				format.json {render json: @list.errors}
			end
		end
	end

	def update
		@list = @user.lists.find(params[:id])

		items = @list.items.create(params[:items])
		if items
			respond_to do |format|
				format.html
				format.json{render :json => {:items => items}, :status => :ok, :location => @list}
			end
		end
	end

	def edit
		@list = @user.lists.find(params[:id])
		@breadcrumbs = [@list.title, 'Edit']
	end

	def checked
		@list = @user.lists.find(params[:list_id])
		Item.where(list_id: params[:list_id], done: true).delete_all
		respond_to do |format|
			format.html {redirect_to @list}
			format.json {render nothing: true}
		end
	end
end

app/controllers/pages_controller.rb
class PagesController  < ApplicationController
	before_action :recent_lists

	def about
		@breadcrumbs = ['About']
	end

	def contact
		@breadcrumbs = ['Contact']
	end

	def recent_lists
		if session[:user_id]
			@user = User.find(session[:user_id])
			@recent_lists = @user.lists.order("created_at DESC").limit(10) if @user
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_username(params[:username])
  	if user && user.authenticate(params[:password])
  		respond_to do |format|

  			format.json do
  				token = user.auth_tokens.create
  				render json: token
  			end

  			format.html do
		  		session[:user_id] = user.id
		  		redirect_to root_url
		  	end
	  	end
  	else

      respond_to do |format|
  		  format.html do
          flash.now.alert = "Invalid username or password. Please try again."
  		    render 'new'
        end

        format.json do
          render json: {"error" => "Invalid username or password. Please try again."}
        end
      end
  	end
  end

  def destroy
  		respond_to do |format|
  			format.html do
			  session[:user_id] = nil
			  redirect_to root_url
			end

			format.json do
				authenticate_or_request_with_http_token do |token, options|
					token = AuthToken.find_by_token(token)
					if token
						token.destroy
						head :ok
					end
				end
			end
		end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user].permit(:username,:password,:password_confirmation))
  	if @user.save
  		redirect_to root_url, :notice => "Registration successful"
  	else
      if @user.errors.any?
        flash.now.alert = @user.errors.full_messages[0]
      end
  		render "new"
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	private

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/list_helper.rb
module ListHelper

	def checked_list_path(list)
		return "/list/#{list.id}/checked"
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_item.html.erb
<% if item.done %>
	<div class="list-group-item checked list-item" data-id="<%=item.id%>">
	<%= item.name %>
<% else %>
	<div class="list-group-item list-item" data-id="<%=item.id%>">
	<%= item.name %>
<% end %>
</div>

app/views/layouts/application.html.erb
<?xml version="1.0"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>Damn Simple Todo | Homepage</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <%= favicon_link_tag 'favicon.ico' %>
      <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
     	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  		<%= csrf_meta_tags %>
</head>

<body>

  <%= render "parts/header" %>

  <div class="main">
    <%= render "parts/breadcrumb" %>

    <% if flash.any? %>
      <%= render partial: "parts/flash", locals: {messages: [flash.alert]} %>
    <% end %>

    <div id="content">

        <%= yield %>
      <%= render "parts/sidebar" %>
    </div>
  </div> <!-- /main -->
</body>
</html>

app/views/list/_lists.html.erb
<!-- this file is sort of a hack until I implement a single page app -->
<div class="list-group">
  <% @lists.each do |list| %>
      <a class="list-group-item <%= "active" if list.id == selected_id %>" href="<%=list_path list.id%>">
        <span class="badge"><%=list.items.count%></span>
          <span class="list-title"><%=list.title%></span>
      </a>
  <% end %>
</div>

app/views/list/edit.html.erb
<div class="mid-pane panel panel-primary">
  <span id="data" data-id="<%= @list.id%>"></span>
  <div class="panel-heading">
    <i class="fa fa-pencil"></i> <%=@list.title%>
  </div>
  <div class="panel-body">
    <textarea rows="20" id="list" class="form-control" placeholder="New line separated list items" autofocus></textarea>
    <br>
    <button id="add" class="btn btn-primary center-block">Add</button>
    <br>
  </div>
</div>

app/views/list/index.html.erb
<div class="list-nav-index list-nav">
  <%= render partial: "list/lists", locals: {selected_id: nil} %>
</div>

<div class="mid-pane list-pane list-group list-pane-index">
  <div class="list-group-item active">
    <i class="fa fa-list"></i>  Lists
  </div>
  <div class="list-group-item">Please select a list</div>
</div>

app/views/list/new.html.erb
<div class="mid-pane panel panel-primary">
  <div class="panel-heading">
    <i class="fa fa-floppy-o"></i> Create
  </div>
  <div class="panel-body">
    <input type="text" id="title" class="form-control" placeholder="Title" autofocus>
    <br>
    <textarea rows="20" id="list" class="form-control" placeholder="New line separated list items"></textarea>
    <br>
    <button id="save" class="btn btn-primary center-block">Save</button>
    <br>
  </div>
</div>

app/views/list/show.html.erb
<div class="list-nav-show list-nav">
  <%= render partial: "list/lists", locals: {selected_id: @list.id} %>
</div>

<div class="mid-pane list-pane list-group">
  <div class="list-group-item active">
      <i class="fa fa-list"></i> <%=@list.title%>
      <ul class="nav nav-pills list-edit">
        <li class="dropdown">
          <div class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
              <i class="fa fa-2x fa-caret-down"></i>
          </div>
          <ul class="dropdown-menu">
            <li>
              <a href="<%=edit_list_path(@list)%>">
                <i class="fa fa-pencil fa-fw"></i> Add
              </a>
            </li>
            <li>
              <a href="<%=checked_list_path(@list)%>" data-method="delete" rel="nofollow">
                <i class="fa fa-eraser fa-fw"></i> Clear
              </a>
            </li>
            <li>
              <a href="<%=list_path(@list)%>" data-method="delete" rel="nofollow">
                <i class="fa fa-trash fa-fw"></i> Delete
              </a>
            </li>
          </ul>
        </li>
      </ul>
  </div>
  <%=render @list.items%>
</div>

<!-- Mobile only -->
<div class="action-bar">
  <a href="<%=edit_list_path(@list)%>" class="action-button">
    <i class="fa fa-pencil fa-2x"></i><br>Add
  </a>
  <a href="<%=checked_list_path(@list)%>" data-method="delete" rel="nofollow" class="action-button">
    <i class="fa fa-eraser fa-2x"></i><br>Clear
  </a>
  <a href="<%=list_path(@list)%>" data-method="delete" rel="nofollow" class="action-button">
    <i class="fa fa-trash fa-2x"></i><br>Delete
  </a>
</div>

app/views/pages/about.html.erb
<div class="mid-pane mobile-info">
    <h2>About</h2>
    I started creating this website in my free time because I just wanted a simple list application that did two things. The first was let me paste a list of new line delimited items into a text box and create a list from that. The second was sync these lists to my mobile phone.
    I have a native android app but currently I have stopped maintaining and adding features to it in favor of the new mobile first layout that you see here.
    I may pick up development on native apps for the future but for now this is all you get. <br><br>
    <h2>Attribution</h2>
    Bootstrap / Bootswatch <br>
    Font-awesome
</div>

app/views/pages/contact.html.erb
<div class="mid-pane mobile-info">
    <h2>Contact</h2>
    email - jllankfo (at) ncsu (dot) edu
</div>

app/views/pages/unauthorized.html.erb
<div class="mid-pane mobile-info">
  Please <%= link_to "log in", log_in_path %> to see this page.
</div>

app/views/parts/_breadcrumb.html.erb
<% if @breadcrumbs %>
  <ul class="breadcrumb">
    <li><a href="/">Home</a></li>
      <% @breadcrumbs.each do |crumb| %>

        <% if crumb == @breadcrumbs[-1] %>
          <li class="active">
            <%=crumb%>
          </li>
        <% else %>
          <li><a href="/"><%=crumb%></a></li>
        <% end %>
      <% end %>
  </ul>
<% end %>

app/views/parts/_flash.html.erb
<% if messages.any? %>
    <% messages.each do |msg| %>
      <div class="alert alert-dismissible alert-danger">
        <button type="button" class="close" data-dismiss="alert"><i class="fa fa-times"></i></button>
        <strong>Ruh-Roh!</strong> <%=msg%>
      </div>
    <% end %>
<% end %>

app/views/parts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="custom-navbar-container container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">DamnSimpleTodo</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Lists<span class="sr-only">(current)</span></a></li>
        <li><a href="/list/new">Create</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/contact">Contact</a></li>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <%=current_user.username.capitalize%><span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Logout', log_out_path %></li>
            </ul>
          </li>
	      <% else %>
          <li><%= link_to 'Register', new_user_path %></li>
          <li><%= link_to 'Log in', log_in_path %></li>
	      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/parts/_sidebar.html.erb
<div id="recent-lists">
  <div class="panel panel-default">
    <div class="panel-heading">Recent Lists</div>
    <div class="panel-body">
      <%
      if @recent_lists
          @recent_lists.each do |list| %>
            <div><a href="<%= list_path list.id%>">
              <span class="list-title"><%= list.title %> </span>
            </a>
              <small class="recent-time">
                <%=list.created_at.strftime("%m/%d/%y")%>
              </small>
            </div>
          <% end %>
      <% else  %>
        No lists to display.
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="mid-pane panel panel-primary">
  <div class="panel-heading">
    <i class="fa fa-newspaper-o"></i> Register
  </div>
  <div class="panel-body">
    <div class="user-form center-block">
      <%= form_for @user do |f| %>
      	<p>
      		<%= f.text_field :username, class: 'form-control', placeholder: "Username", :autofocus => true %>
      	</p>
      	<p>
      		<%= f.password_field :password, class: 'form-control', placeholder: "Password" %>
      	</p>
      	<p>
      		<%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Confirmation" %>
      	</p>
      	<%= f.submit "Register", class: 'btn btn-primary btn-login'%>
      <% end %>
    </div>
  </div>
</div>